BEGIN;

CREATE SCHEMA IF NOT EXISTS Bot;

-- Tabela legada de configuração multi-instância; a instância única vem do .env.
DROP TABLE IF EXISTS Bot.Instancias;

CREATE TABLE IF NOT EXISTS Bot.Cliente (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(250),
  telefone VARCHAR(80),
  sender VARCHAR(250),
  instancia VARCHAR(120) NOT NULL,
  fbEventId VARCHAR(100),
  origem VARCHAR(50),
  createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cliente_telefone_instancia
  ON Bot.Cliente (telefone, instancia)
  WHERE telefone IS NOT NULL;

-- Flag operacional (não é status comercial/lead): indica se a IA está pausada
-- para esse cliente. Persistida para sobreviver a restart do processo.
ALTER TABLE Bot.Cliente ADD COLUMN IF NOT EXISTS iaPausada BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS Bot.Mensagens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clienteId INTEGER,
  mensagemId VARCHAR(100),
  mensagem TEXT,
  type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  fromMe BOOLEAN NOT NULL,
  mensagemRespostaId VARCHAR(100),
  mediaUrl VARCHAR(1000),
  celularEnvio VARCHAR(50),
  celularRecebimento VARCHAR(50),
  createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_mensagens_cliente
    FOREIGN KEY (clienteId) REFERENCES Bot.Cliente(id)
);

CREATE INDEX IF NOT EXISTS ix_mensagens_clienteid
  ON Bot.Mensagens (clienteId);

CREATE INDEX IF NOT EXISTS ix_mensagens_mensagemid
  ON Bot.Mensagens (mensagemId);

COMMIT;
